### ISSUE TITLE
같은 현상의 반복이네요 ㅎㅎ

### ISSUE THREAD

**Issue by hanwong** [yamoo9/FDS#10]
2기 피드백을 봤는데 ... 같은 현상의 반복이네요 ㅎㅎㅎ
README 파일에 댓글 달고 싶은데 깃헙은 댓글이 없네요 ㅋㅋ

**Comment by yamoo9** [comment]
ㅎㅎㅎ @hanwong 맞아요 :smile:
지승님께 부탁해서 노트 촬영한 후 공유해야 할 듯 하네요 ㅎ
