### ISSUE TITLE
오타 있어요

### ISSUE THREAD

**Issue by simonseo** [yamoo9/FDS#2]
https://github.com/yamoo9/FDS/tree/master/DAY21#alignment

Flex box 에 대한 설명 중에 alignment 부분에
`felx-end`라고 나온 걸 `flex-end`라고 바꿔줘야 할 것 같습니다

**Comment by yamoo9** [comment]
@simonseo [flex-end → flex-end 오타 수정](https://github.com/yamoo9/FDS/commit/48592cd0d00aaf53a5f860bc1dbc30b577eba69b) 했습니다. 👍
