### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by simonseo** [yamoo9/FDS#3]
https://github.com/yamoo9/FDS/tree/master/DAY24#보간법interpolation
여기에 오타가 몇가지 있네요.
1. 미디어쿼리에서 interpolation하는 변수에 `$`가 빠져있습니다.
   `@media #{media-lg}`
2. 프린트 환경 미디어쿼리를 위해 만든 변수값이
   `$media-print: "screen and (min-width: 21px)"` 라고 선언되어있는데
   `$media-print: "print and (min-width: 21px)"` 로 바꿔야 할 것 같습니다.

**Comment by yamoo9** [comment]
수정 반영했습니다. ^^ 고맙습니다!
