### ISSUE TITLE
.is-nesting 클래스와 하위 .col 의 offset 속성

### ISSUE THREAD

**Issue by jungminji** [yamoo9/FDS#55]
.is-nesting 클래스가 붙여진 row는 클래스, 속성, pseudo-class 구성되어 있어서 하위 첫번째 div.col 에 offset 을 설정하면 스타일이 적용되지 않습니다.  첫번째를 제외한 나머지 col 은 정상적이고, 마지막 col은 margin-right 라 margin-left 값에는 영향을 안 받네요

<img width="314" alt="screen shot 2017-05-23 at 6 38 43 pm" src="https://cloud.githubusercontent.com/assets/9646260/26348253/244e5398-3fe7-11e7-83dc-030643ed5e88.png">

위와 같은 상황에서는 어떤 방법이 가장 좋은 해결 방법인가요?

offset 클래스에 !important 를 설정하는 건 임시방편 느낌이네요

**Comment by yamoo9** [comment]
우선순위에서 밀려 문제가 생겼군요.
아래와 같은 방법을 사용하여 우선순위를 높이면 문제가 해결됩니다. ^^

```sass
@for $i from 1 through $columns {
  .is-#{$i}  {
    width: column-width($i);
  }
  // .is-offset-*
  .is-offset-#{$i} {
    $offset-width: offset-width($i);
    margin-left: $offset-width;
    // .is-nesting .is-offset-*
    .is-nesting &:first-child {
      margin-left: $offset-width - $half-gutter-width;
    }
  }
}
```
