### ISSUE TITLE
DAY 34 오타 발견했습니다.

### ISSUE THREAD

**Issue by jyoungcode** [yamoo9/FDS#6]
for문에서 
               ↘ (여기 오타.. ' , ' 으로 처리) 
for( var i = 0;, boo = false; i > 10; i++ ) {

다들 아실테지만 그래도 혹시나 싶어서 말씀드립니다.;;

**Comment by jyoungcode** [comment]
for문에서 
↘ (여기 오타.. ' , ' 으로 처리 / i < 10; 으로 수정) 
for( var i = 0;, boo = false; i > 10; i++ ) {

i < 10으로 바꿔야 하는게 맞죠.?

**Comment by goohooh** [comment]
네 맞습니다. 수정하겠습니다
